
data_loader:
  path: "/home/sv/Documents/time-series-analysis/weatherkit_plus_load.csv" # replace with your own path
  remove_outliers: True
  normalize: False
  num_lags: 3 # number of load lag features to compute
  

model:
  ensemble: False
  xgboost:
    objective: "reg:squarederror" # "reg:pseudohubererror"
    n_estimators: 700
    learning_rate: 0.05
    max_depth: 4
    min_child_weight: 1
    subsample: 0.9
    colsample_bytree: 0.9
    random_state: 42

  lightgbm:
    num_leaves: 292
    max_depth: 10
    learning_rate: 0.0472482796526682
    min_data_in_leaf: 32
    lambda_l1: 1.2927743955065722e-05
    lambda_l2: 1.1572147572170338e-07
    feature_fraction: 0.977436398539705
    bagging_fraction: 0.5759941094908022
    bagging_freq: 9
    objective: regression

  catboost:
    iterations: 1000
    learning_rate: 0.13786576194363528
    depth: 7
    loss_function: "RMSE"
    l2_leaf_reg: 7.76873502580487e-08
    bagging_temperature: 0.7329476073761131
    random_strength: 0.0627338404379398

visualizer:
  alpha: 0.7




